### ISSUE TITLE
polymorphic models can't be fetched by id

### ISSUE THREAD

**Issue by bernharduw** [AmpersandJS/ampersand-collection-rest-mixin#14]
When I define a collection's model as a function, the `fetchById()` function fails. The `idAttribute` of the model property is used to construct a new model that is then fetched. In this case the model is no ampersand-state, but of type function, so it has no idAttribute.

This happens in this line: https://github.com/AmpersandJS/ampersand-collection-rest-mixin/blob/master/ampersand-collection-rest-mixin.js#L87.

I am not sure what the best solution would be for this:
- Should the idAttribute be defined on the collection itself?
- Or should the fetchById function accept an additional parameter `idAttribute`? (which would also apply to `getOrFetch()`).
- Or should an empty model be created and then the idAttribute be read on the instantiated model?

**Comment by bernharduw** [comment]
Maybe the `mainIndex` of the collection can be used as a fallback.

**Comment by pgilad** [comment]
@bernharduw What do you expect the `idAttribute` of the model to be (in the non ampersand-state)?
If you are creating a function constructor, why not just add a property of `idAttribute` to it?

**Comment by pgilad** [comment]
@bernharduw I think https://github.com/AmpersandJS/ampersand-collection-rest-mixin/blob/master/ampersand-collection-rest-mixin.js#L87

`idObj[this.model.prototype.idAttribute] = id;`

should be changed to:

`idObj[this.model.idAttribute || this.model.id] = id;`

But this will fail with `idAttribute` as a false value (0, '', etc).

thoughts?

**Comment by pgilad** [comment]
@bernharduw Please validate - we switched to using `mainIndex`
