### ISSUE TITLE
Accepting a transform

### ISSUE THREAD

**Issue by lifehackett** [AmpersandJS/ampersand-collection-rest-mixin#24]
What do you think about amending `ampersand-collection-rest-mixin` to accept a transform function.  In my case I need to transform the results of my rails API which are in `snake_case` into `camelCase` which is the JS convention for my models.  Another popular use case might be handling an enveloped API response.

For example, the existing `fetch()` function would be updated to something like this

```js
        var transform = this.transform;

        options.success = function(resp) {
            var method = options.reset ? 'reset' : 'set';
            if (transform) {
               resp = transform(resp);
            }
            collection[method](resp, options);
            if (success) success(collection, resp, options);
            collection.trigger('sync', collection, resp, options);
        };
```

A similar update would need to be made to `ampersand-model` to handle, in my case, the reverse mapping. 

You could then incorporate a mixin (e.g. snakeToCamelTransformMixin) that defines the transform function or define your own.

I'm happy to make the updates in a PR, but wanted to get your buy in before I did.

**Comment by cdaringe** [comment]
I believe your needs can already be achieved by defining a 'parse' function on your rest collection.  Did you see the bit on it in the docs?

**Comment by lifehackett** [comment]
Hmm, I did not (and still don't).  I see a parse function on ampersand-state and on the options object passed in to fetch, but not on rest-collection.  http://ampersandjs.com/docs#ampersand-rest-collection

**Comment by cdaringe** [comment]
Apologies, it is in state.  Whenever your API returns data and goes to create a model, before the model is injected into the collection, the object for each record will first be passed into parse, and mutated as you see fit. In this regard, It can be used as a transform, or be used to proxy transforms!

**Comment by lifehackett** [comment]
Ah ok.  That would solve transforming individual properties, but wouldn't solve nested collections with multi word names.  Additionally, I'd like to transform the request in the case of `POST, PUT, PATCH`.

**Comment by cdaringe** [comment]
Hey @lifehacket, it might actually handle your collections too.  I haven't tested or dug thru the source, but if your collection has a model property defined on it, and that model reference also has a parse, I am thinking that each raw obj from your API will also get parsed, even its nested.

State.serialize should handle your outbound transforms!

**Comment by pgilad** [comment]
See https://github.com/AmpersandJS/ampersand-collection/blob/master/ampersand-collection.js#L34-L36

`parse` works both for model & collections.
