### ISSUE TITLE
Add method to sync "dirty" models?

### ISSUE THREAD

**Issue by bryanspears** [AmpersandJS/ampersand-collection-rest-mixin#26]
When persisting a collection to an endpoint, I often find myself doing the following

```javascript
// Persists any dirty children
	save: function () {
		var updates = this.filter(function (model) {
			return model.hasChanged();
		});

		this.sync('update', this, {attrs: updates});
	}
```

1. Is there a better/cleaner/faster way to do this?
2. Is this something that should be included as part of ampersand's restful collection?
3. Am I breaking the pattern by doing this?

This seems to be more discussion-oriented, but I feel there's a place for such a method.

**Comment by pgilad** [comment]
I don't see a save method for a collection making any sense. Unless you are trying to orchestrate sequential (or parallel) ajax, which is not the case here.

Regarding dirty properties for a *PATCH* request, there is a lot of debate here, and `hasChanged()` is a terrible solution IMO for detecting changed properties (it only detects the last property that changed since the last set).

A better solution might be to diff 2 js objects (might be done using `changedAttributes`)

**Comment by bryanspears** [comment]
Thanks, that's a good fact to know about hasChanged.

Parallel ajax PUT is not what I was trying to accomplish here. What this does (or should do) is generate a list of json objects and send them to the collections endpoint in bulk to avoid flooding parallel PUTs to the server. The use case is I have a table of editable elements, and I don't want to save onchange, but rather when where is a save action. This would then find all changed models and send them up to an API endpoint.

**Comment by pgilad** [comment]
I see. You might want to find a more stable diffing mechanism. 1 that I can think of is when you are initializing the models have:
`this.listenToOnce(this, 'change', () => this.isDirty = true);`

and the server would just filter through all dirty models.

**Comment by bryanspears** [comment]
I forgot to mention, my method does work as I want. I only used hasChanged() to indicate that there is change. By using filter() I get the entire, current model returned into an array of changed models which I then send up to the server.

So, yeah, it really isn't the best. For example, if they changed values back to original values this method would still consider the model dirty. I guess that'd be an issue in your suggestion as well.

**Comment by pgilad** [comment]
I personally don't see room for a `save` method in the base module. It's fine to add it in another mixin or perhaps even improve documentation to instruct on how to do this.

Me personally - I've never had to do a PUT request to replace an entire collection.
