### ISSUE TITLE
models with url in props causes error

### ISSUE THREAD

**Issue by webmasterkai** [AmpersandJS/ampersand-collection-rest-mixin#3]
If you have a model that has url within props

```
module.exports = AmpersandModel.extend({
props: {
    id: 'any',
    firstName: ['string', true, ''],
    lastName: ['string', true, ''],
    coolnessFactor: ['number', true, 5],
    url: 'string'
},
```

and you set a url in the collection 

```
var Collection = require('ampersand-rest-collection');
var Person = require('./person');

module.exports = Collection.extend({
    model: Person,
    url: '/api/people'
});
```

and then you try to use getOrFetch on the collection

```
        app.people.getOrFetch(spec.id, function (err, model) {
            if (err) alert('couldnt find a model with id: ' + spec.id);
            self.model = model
        });
```

It fails with error

> Uncaught Error: A "url" property or function must be specified 

I took the demo app that's installed with the ampersand command and added the `url: 'string'` to the model person.js and removed the `{all: true}` option to the `getOrFetch()` function in person-view.js. If you navigate to http://localhost:3000/person/4 you'll see it's broken...

**Comment by tnguyen14** [comment]
@kamilogorek this is currently the `serialize` method on `ampersand-state` (line 83-94):

```js
    // Serialize is the inverse of `parse` it lets you massage data
    // on the way out. Before, sending to server, for example.
    serialize: function () {
        var res = this.getAttributes({props: true}, true);
        _.each(this._children, function (value, key) {
            res[key] = this[key].serialize();
        }, this);
        _.each(this._collections, function (value, key) {
            res[key] = this[key].serialize();
        }, this);
        return res;
    },
```

Would you recommend overriding it this way?

```js
    // Serialize is the inverse of `parse` it lets you massage data
    // on the way out. Before, sending to server, for example.
    serialize: function () {
        var res = this.getAttributes({props: true}, true);
        _.each(this._children, function (value, key) {
            res[key] = this[key].serialize();
        }, this);
        _.each(this._collections, function (value, key) {
            res[key] = this[key].serialize();
        }, this);
        res.url = res.endpointUrl;
        return res;
    },
```

**Comment by kamilogorek** [comment]
@tnguyen14 if you only want to override a specific model, then you don't have to touch state's serialize at all.

```
var MyModelWithUrl = AmpersandModel.extend({
    serialize: function () {
        var res = this.getAttributes({props: true}, true);
        res.url = res.endpointUrl;
        return res;
    }
});
```

**Comment by tnguyen14** [comment]
@kamilogorek I did that, and back to getting the same error mentioned in this issue `Uncaught Error: A "url" property or function must be specified`. I feel like overriding `serialize` is a little too early?

**Comment by kamilogorek** [comment]
@tnguyen14 could you please provide an example on requirebin or anywhere else so I can take a look?

**Comment by tnguyen14** [comment]
I am trying to do that, but I decided to change my backend to not use `url` instead, and now it isn't quite reproducing the problem.. hmm..

**Comment by neilbaylorrulez** [comment]
Not sure why this issue would be marked as "closed" (as its a definite limitation of the framework, given the "i don't own the backend" situation many of your users are in) but thought I'd update with a way to actually "sync" with your API in the event that your backend requires 'url' as the parameter:

My Model:
```
   props: {
    ...
    myUrl: ['string', false, ''], //this is my "url" property
    ...
  },
  parse: function (data) {
    data.myUrl = data.url;
    delete data.url;
    return data;
  },
  save: function () {
    arguments[0].url = arguments[0].myUrl;
    AmpersandModel.prototype.save.apply(this, arguments);
  },
```

**Comment by HenrikJoreteg** [comment]
@neilbaylorrulez the serialize method expects you to extract the data you want on the "way out" yourself.

By default it looks like this:

```js
    serialize: function () {
        var res = this.getAttributes({props: true}, true);
        forEach(this._children, function (value, key) {
            res[key] = this[key].serialize();
        }, this);
        forEach(this._collections, function (value, key) {
            res[key] = this[key].serialize();
        }, this);
        return res;
    },
```

You could do something like this:

```js
    serialize: function () {
        // get the starting data
        var data = Model.prototype.serialize.call(this);
        data.url = data.myUrl;
        delete data.myUrl;
        return data;
    },
```

Having said this, I do think "url" is common enough that perhaps we should consider renaming the default

**Comment by neilbaylorrulez** [comment]
@HenrikJoreteg thanks for the update - i will try your suggestion and report back if i'm having any issues.

BTW - I agree that url isn't common enough to rename the default.
What i would suggest is to make it configurable. The result would be much "cleaner" for users of the framework, and it would bring assurance to users that their code is future-proof.
