### ISSUE TITLE
`getOrFetch` cause `TypeError: Cannot read property 'bind' of undefined`

### ISSUE THREAD

**Issue by wisonye** [AmpersandJS/ampersand-collection-rest-mixin#42]
I found a bug which I think  **you guys should fix it** !!! :)

For example if somebody call it like this `someModel.getOrFetch('someModelId')`, pay attention to my comment there:

```javascript
getOrFetch: function (id, options, cb) {
    // This will FORCE the 'cb' equal to 'options' (but the point is 'options' is 'undefined')
    if (arguments.length !== 3) {
        cb = options;
        options = {};
    }
    
    var self = this;
    var model = this.get(id);
    
    if (model) {
        // Then if the 'model' is already exists, code below will run, but at this moment 'cb' is 'undefined' which will cause exception:
        // TypeError: Cannot read property 'bind' of undefined
        return window.setTimeout(cb.bind(null, null, model), 0);
    }
    
    if (options.all) {
        //preserve original `options.always`
        var always = options.always;
        options.always = function(err, resp, body) {
            if (always) always(err, resp, body);
            if (!cb) return;
            
            var model = self.get(id);
            var err2 = model ? null : new Error('not found');
            cb(err2, model);
        };
        return this.fetch(options);
    } else {
        return this.fetchById(id, options, cb);
    }
}
```

**Comment by dhritzkiv** [comment]
Hi, @wisonye. Calling `getOrFetch` without a callback (in either the second or third argument position) is unsupported, as the method needs to pass the returned model somewhere. If you need similar behaviour to `getOrFetch` without a callback, I'd suggest the `fetchById` method, which you should be able to call without a callback.

If you think the `getOrFetch` method can be improved by adding more checks, including checks to see that callback is a function, please submit a Pull Request with your code improvements :)
